version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    entrypoint: ["/app/entrypoint.sh"]
    command: ["gunicorn", "--bind", "0.0.0.0:8001", "config.wsgi:application"]

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_PATH=./
      - PORT=3001
    depends_on:
      - backend
    command: [ "npm", "run", "start" ]  # Run built app
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3001/ || exit 1" ]
      interval: 30s
      retries: 3
      timeout: 10s
