version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    restart: always
    ports:
      - "8001:8001"
    networks:
      - app_network
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    entrypoint: ["/app/entrypoint.sh"]
    command: ["gunicorn", "--bind", "0.0.0.0:8001", "config.wsgi:application"]

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    restart: always
    ports:
      - "3001:3001"
    networks:
      - app_network
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NODE_PATH=./
      - PORT=3001
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3001/ || exit 1" ]
      interval: 30s
      retries: 3
      timeout: 10s
